export type Language = 'ar' | 'en';

export const localizationData = {
  ar: {
    // Nav & Common Tabs
    app_title: "صيدلية الرعاية الذكية",
    app_subtitle: "نظام المراقبة والصرف الدوائي للمقيمين ذوي الاحتياجات الخاصة",
    dashboard: "لوحة التحكم 📊",
    inventory: "إدارة المخزن 📦",
    alternatives: "البدائل العلاجية 🔍",
    dispense: "صرف الأدوية 💊",
    residents: "المقيمون 👥",
    behavior: "السلوك والنفسية 🧠",
    companies: "شركات الأدوية 🏢",
    users: "إدارة المستخدمين ⚙️",
    welcome: "مرحباً بك،",
    role: "الصفة:",
    security_level: "مستوى الحماية: عالي جداً",
    client_ip: "عنوان الـ IP الحالي:",
    logout: "تسجيل الخروج",
    dark_mode: "الوضع الداكن",
    light_mode: "الوضع المضيء",
    save: "حفظ",
    cancel: "إلغاء الأمر",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    search: "بحث...",
    actions: "الإجراءات",
    all: "الكل",
    no_data: "لا توجد بيانات متاحة حالياً",
    success_msg: "تمت العملية بنجاح!",

    // Dashboard Scorecard
    total_val: "إجمالي القيمة المالية للمخزون",
    total_items: "إجمالي الأصناف الفريدة:",
    dispensed_qty: "كميات الأدوية المصروفة فعلياً",
    dispense_count: "عدد عمليات الصرف الإجمالية:",
    near_expiry: "أدوية قريبة انتهاء الصلاحية",
    alert_config: "التنبيه مضبوط قبل:",
    days_unit: "يوماً",
    critical_expired: "أدوية منتهية الصلاحية / عجز",
    expired_count: "منتهية:",
    critical_count: "حرجة:",
    dispense_unit: "وحدة صرف",
    items_unit: "أصناف",
    emergency_cases: "حالات طارئة",

    // Dashboard Actions
    new_dispense_btn: "تسجيل صرف دواء جديد",
    wa_report_btn: "إرسال تقرير واتساب مجاني 📲",
    simulate_alerts_btn: "محاكاة إشعارات انتهاء الصلاحية",

    // Dashboard Charts
    monthly_consumption: "معدل الاستهلاك والصرف الدوائي الشهري",
    monthly_desc: "مراقبة الكميات والجرعات المصروفة شهرياً لمقيمين المركز وقيمتها المالية",
    distribution_title: "توزيع المخزون الدوائي الحالي",
    distribution_desc: "توزيع كميات الأدوية النشطة بناءً على التصنيف العلاجي",
    stable_badge: "مستقر",
    active_stock: "المخزون النشط",
    unit_qty: "وحدة",
    sar: "ر.س",

    // Manufacturer Charts
    manufacturer_stock: "تحليل مخزن الصيدلية حسب الشركة المصنعة",
    manufacturer_stock_desc: "إجمالي القيمة المالية والكميات المتوفرة في المستودع لكل شركة إنتاج",
    manufacturer_dispense: "معدلات سحب وصرف أدوية الشركات للمقيمين",
    manufacturer_dispense_desc: "إجمالي الوحدات والجرعات العلاجية المنصرفة فعلياً والتابعة لإنتاج كل شركة",
    total_value_chart: "القيمة المالية (ر.س)",
    total_qty_chart: "الكمية المتوفرة",
    actual_dispensed_chart: "الكمية المصروفة فعلياً",

    // Forecasting & Near-Expiry Panels
    predictive_title: "نظام التنبؤ الذكي لنفاد المخزون المستقبلي",
    predictive_desc: "تحليل سرعة الصرف والتنبؤ التلقائي بالموعد المتوقع لنفاد الكميات",
    predictive_safe: "مستويات المخزون كافية وآمنة بالكامل للـ 60 يوماً القادمة!",
    depletion_critical: "نفاد حرج 🚨",
    depletion_warning: "تزويد مطلوب ⚠️",
    monthly_draw: "معدل السحب الشهري:",
    available_qty: "الكمية المتاحة حالياً:",
    expected_depletion: "النفاد المتوقع: خلال",
    expected_days: "يوماً فقط!",
    near_expiry_meds_title: "الأدوية الأقرب لانتهاء الصلاحية",
    near_expiry_safe: "جميع الأدوية في مخزن الصيدلية صالحة وتخضع للمراقبة التلقائية المستمرة.",
    expire_after: "ينتهي بعد:",
    days_left: "يوم فقط!",
    expired_already: "منتهي بالفعل! 🚨",

    // Alternatives Directory Tab
    alternatives_title: "دليل بدائل الأدوية الذكي",
    alternatives_desc: "ابحث عن أي دواء لمعرفة بدائله العلاجية المتوفرة وحالة المخزون العيني له",
    search_label: "اختر أو ابحث عن اسم الدواء التجاري أو العلمي:",
    search_placeholder: "اكتب اسم الدواء التجاري أو العلمي للبحث...",
    no_med_matches: "لا يوجد أدوية تطابق هذا البحث",
    manufacturer_label: "الشركة المصنعة:",
    expiry_date_label: "تاريخ انتهاء الصلاحية:",
    unit_price_label: "سعر الوحدة:",
    not_defined: "غير محددة",
    available_alts_label: "البدائل العلاجية المتاحة والمقترحة في النظام:",
    alts_intro: "تم تدوين البدائل التالية لهذا الدواء كبدائل علاجية بديلة يمكن صرفها عند الحاجة ونفاد المخزون:",
    registered_alt: "اسم البديل المسجل",
    available_in_stock: "متوفر في المستودع ✅",
    not_available_in_stock: "غير متوفر بالمستودع عيناً ❌",
    view_alt_details: "انقر لعرض تفاصيل هذا البديل 🔍",
    no_alts_registered: "لا توجد بدائل مسجلة لهذا الدواء",
    no_alts_registered_desc: "يمكنك الدخول إلى إدارة المخزن وتعديل بيانات الدواء لإدخال بدائل طبية وعلاجية له.",
    no_med_selected: "لم يتم اختيار أي دواء بعد",
    no_med_selected_desc: "استخدم مربع البحث بالأعلى لاختيار دواء، وسيعرض لك النظام كافة التفاصيل وبدائله العلاجية وحالة توفرها في المخزن العيني.",

    // Inventory Tab
    inventory_title: "إدارة مخزون ومستودع الصيدلية",
    inventory_subtitle: "إدخال الأصناف الدوائية الجديدة، تحديد التنبيهات، ومتابعة القيمة المالية للمخزون عيناً",
    add_new_med: "إضافة دواء جديد للمستودع +",
    commercial_name: "الاسم التجاري للدواء",
    scientific_name: "الاسم العلمي للدواء",
    unit_label: "وحدة الصنف",
    category_label: "الفئة العلاجية",
    quantity: "الكمية المتاحة",
    unit_price: "سعر الوحدة",
    expiry_date: "تاريخ الصلاحية",
    registered_manufacturer: "الشركة المصنعة",
    alt_medicines: "البدائل العلاجية",
    search_inventory: "ابحث بالاسم التجاري أو العلمي للدواء...",
    all_categories: "جميع الفئات العلاجية",
    filter_stock: "تصفية حالة الكميات والصلاحية",
    all_items: "كل الأصناف المخزنة",
    critical_stock_filter: "أصناف مخزون حرج (15 علبة وأقل)",
    expired_items_filter: "أصناف منتهية الصلاحية بالفعل",
    expiring_soon_filter: "أصناف تنتهي قريباً (30 يوماً)",
    companies_sub_tab: "دليل شركات الأدوية المعتمدة 🏢",
    companies_sub_desc: "إدارة وتسجيل شركات توريد وتصنيع الأدوية ومعلومات الاتصال الرسمية بها",
    add_new_company: "تسجيل شركة أدوية جديدة +",
    company_name: "اسم الشركة الموردة/المصنعة",
    country: "دولة المنشأ",
    contact_person: "مسؤول المبيعات",
    phone: "رقم الهاتف والاتصال",
    email: "البريد الإلكتروني",
    notes: "ملاحظات إضافية",
    search_companies: "البحث في دليل شركات الأدوية...",

    // Dispense Tab
    dispense_title: "سجل عمليات صرف الأدوية وجدول التوزيع اليومي",
    dispense_subtitle: "مراقبة تسليم الأدوية والجرعات اليومية للمقيمين، وتوثيق توقيع المشرفين والصيادلة",
    record_new_dispense: "توثيق عملية صرف دواء جديدة +",
    resident_name: "اسم المقيم المستلم",
    dispensed_med: "الدواء المصروف",
    frequency_label: "التكرار / الجرعة اليومية",
    quantity_dispensed: "الكمية المصروفة",
    dispense_date: "تاريخ الصرف",
    supervisor_sig: "توقيع الصيدلي والمشرف المستلم",
    search_dispense: "البحث باسم المقيم أو الدواء المصروف...",
    no_records_found: "لم يتم العثور على أي سجلات مطابقة للبحث حالياً.",

    // Residents Tab
    residents_title: "ملفات المقيمين الطبية وجداول الصرف المعتمدة",
    residents_subtitle: "الوصول للملفات الطبية التفصيلية للمقيمين ذوي الاحتياجات الخاصة، ومتابعة جداول أدويتهم وسلوكهم اليومي",
    add_new_resident: "إضافة مقيم جديد بالمركز +",
    resident_id: "الرقم الطبي للمقيم",
    national_id: "رقم الهوية الوطنية",
    age: "العمر",
    floor_room: "الدور والشرق/الغرفة",
    medical_condition: "الحالة الطبية والتشخيص الطبي",
    emergency_phone: "هاتف الطوارئ لذويه",
    actions_resident: "ملف المقيم الطاقي والجرعات 📋",
    search_residents: "البحث باسم المقيم، الرقم الطبي، أو الهوية الوطنية...",

    // Resident File Modal (ملف المقيم)
    resident_profile_title: "الملف الطبي التفاعلي للمقيم:",
    resident_profile_sub: "إدارة شاملة للجرعات الدوائية، المتابعة النفسية، السجل السلوكي، وتوليد تقارير الذكاء الاصطناعي",
    general_info_tab: "البيانات العامة والتشخيص 🩺",
    dosage_schedule_tab: "جدول الجرعات الدوائية (الجرعة اليومية) 📅",
    behavior_tracking_tab: "متابعة السلوك اليومي والتتبع النفسي 🧠",
    ai_analysis_tab: "التحليل الطبي والدوائي بالذكاء الاصطناعي ✨",
    clinical_history: "التحليل السريري للجرعات:",
    add_dose_btn: "إضافة جرعة دوائية جديدة للمقيم +",
    daily_schedule: "الجدول اليومي المعتمد لصرف وجرعات الأدوية:",
    dose_med_name: "الدواء الموصوف",
    dose_amount: "الجرعة المقررة",
    dose_freq: "تكرار الجرعة اليومية",
    dose_status: "الحالة البرمجية وصلاحية الصيدلية",
    dosage_active: "نشط ومعتمد في الملف ✅",
    behavior_logs_title: "سجل تقييم السلوك والتتبع النفسي للمقيم:",
    add_behavior_btn: "تسجيل حالة سلوكية/نفسية جديدة للمقيم +",
    behavior_rating: "مستوى الاستقرار والهدوء",
    behavior_notes: "الملاحظات السلوكية والتوصيات الطبية",
    behavior_date: "تاريخ التقييم",
    stable_green: "مستقر وطبيعي 🟢",
    agitated_orange: "مضطرب / قلق متوسط 🟡",
    anxious_red: "عصبية / تشتت حاد 🔴",
    ai_btn_generate: "توليد التحليل الطبي والاستراتيجي للدواء والمقيم ✨",
    ai_prompt_text: "توليد تقرير استراتيجي بالذكاء الاصطناعي للمقيم:",
    ai_generating: "جاري فحص مخزون الأدوية، وحساب سرعة السحب، ومطابقتها بملف المقيم...",
    ai_report_title: "التقرير الاستراتيجي الوقائي الصادر من نظام صيدلية الرعاية:",

    // Behavior Tab (السلوك والنفسية)
    behavior_title: "التتبع النفسي وتقييم الحالة السلوكية للمقيمين",
    behavior_subtitle: "لوحة تفاعلية لمراقبة استقرار المقيمين اليومي، وسلوكياتهم، وتسجيل الملاحظات للمتابعة الطبية والنفسية",
    resident_field: "المقيم",
    rating_field: "تقييم السلوك",
    notes_field: "الملاحظات وتوجيهات المشرف",
    date_field: "تاريخ ووقت الرصد",
    search_behavior: "البحث باسم المقيم أو حالة السلوك...",
    behavior_rating_chart_title: "توزيع تقييمات السلوك العام للمقيمين بالمركز",

    // User Settings Tab
    users_title: "صلاحيات الوصول وسجلات الأمان الفيدرالية والمراقبة",
    users_subtitle: "التحكم في حسابات الصيادلة، مدراء النظام، والأخصائيين، ومراقبة كافة الحركات الفورية وسجلات الأمان",
    add_new_user: "إضافة مستخدم جديد للنظام +",
    user_name_col: "اسم الموظف / المستخدم",
    email_col: "البريد الإلكتروني",
    role_col: "الصلاحية الطبية",
    status_col: "حالة الحساب",
    ip_allowed_col: "الـ IPs المسموحة للاتصال",
    security_logs_title: "سجل الرقابة والأمان الفيدرالي الفوري (Security Logs):",
    security_logs_desc: "سجل مشفر يسجل كافة عمليات الدخول، الصرف، الإضافة، التعديل وعنوان الآي بي وجهاز الموظف المسؤول لضمان الأمان الفيدرالي الطبي",
    timestamp_col: "التوقيت والزمن الفعلي",
    user_col: "المستخدم المسؤول",
    action_col: "الحركة الطبية أو الأمنية المنفذة",
    ip_col: "عنوان الـ IP والمكان",
    device_col: "بيئة العمل ومتصفح الجهاز",
    search_users_logs: "البحث باسم الموظف أو عنوان الـ IP أو الإجراء المنفذ...",

    // Notification Channel Tab (إعدادات القنوات)
    notif_title: "إعدادات قنوات الإرسال المتقدمة وأنظمة المراقبة الصباحية",
    notif_subtitle: "ربط الصيدلية بالواتساب التلقائي، البريد الإلكتروني للوزارة، وجدولة التنبيهات الدوائية الصباحية الذاتية",
    notif_whats_title: "إعدادات قناة WhatsApp ومحاكي الإشعارات الذاتي:",
    notif_whats_desc: "تفعيل الإرسال التلقائي كرسائل فورية لهواتف الإدارة والوزارة ومسؤولي التوريد عن الأدوية المنتهية أو الحرجة",
    whats_enable: "تفعيل إشعارات الواتساب",
    whats_mode_label: "بوابة إرسال الواتساب المستهدفة",
    whats_number_label: "رقم مستلم إشعارات الواتساب (بالصيغة الدولية)",
    whats_number_placeholder: "مثال: 9665XXXXXXXX",
    ultramsg_inst_label: "معرف نسخة UltraMsg (Instance ID)",
    ultramsg_tok_label: "رمز الدخول لـ UltraMsg (Token)",
    callmebot_api_label: "مفتاح API الخاص بـ CallMeBot",
    wapilot_api_label: "مفتاح API الخاص بـ WAPilot (Token)",
    notif_email_title: "إعدادات قناة البريد الإلكتروني (Google Apps Script Proxy):",
    notif_email_desc: "ربط النظام بسكربت Google المعتمد لإرسال التنبيهات الدورية دون أي تكلفة على حساب الصيدلية",
    email_enable: "تفعيل إشعارات البريد الإلكتروني",
    email_apps_script: "رابط (روابط) Google Apps Script Web App URL",
    email_apps_script_placeholder: "أدخل الرابط، أو عدة روابط تفصلها فواصل لتدويرها آلياً عند تجاوز حد الإرسال لـ Google",
    recipient_email_label: "البريد الإلكتروني المستلم لتقرير الفحص الدوائي",
    recipient_email_placeholder: "مثال: admin@carecenter.gov.sa",

    // Add/Edit Medicine Modals
    add_med_title: "إضافة صنف دواء جديد في مستودع الصيدلية",
    edit_med_title: "تعديل صنف دواء في مستودع الصيدلية",
    commercial_name_req: "الاسم التجاري للدواء *",
    scientific_name_req: "الاسم العلمي للدواء *",
    unit_available: "الكمية المتاحة (وحدة الصنف) *",
    unit_req: "الوحدة *",
    add_unit_link: "+ إضافة وحدة",
    unit_price_req: "سعر الوحدة (ر.س) *",
    expiry_date_req: "تاريخ انتهاء الصلاحية *",
    category_req: "الفئة العلاجية *",
    add_category_link: "+ إضافة فئة",
    manufacturer_req: "الشركة المصنعة للدواء",
    manufacturer_placeholder: "اكتب اسم الشركة أو اختر من القائمة...",
    alts_label: "البدائل المتاحة لهذا الدواء",
    write_alt_placeholder: "اكتب اسم البديل ثم اضغط Enter أو زر الإضافة...",
    add_alt_btn: "إضافة بديل +",
    save_med_btn: "حفظ الدواء في المستودع",
    save_edits_btn: "حفظ التعديلات الطارئة",

    // Toast & Alerts Custom
    confirm_med_delete: "تأكيد حذف الدواء نهائياً",
    confirm_med_delete_desc: "هل أنت متأكد من رغبتك في شطب هذا الدواء نهائياً من مخزون صيدلية الرعاية؟ لا يمكن التراجع عن هذا الإجراء وسيتم إلغاء تتبع الكميات المسجلة.",
    confirm_med_delete_btn: "تأكيد الحذف والشطب",
    confirm_company_delete: "تأكيد حذف شركة الأدوية",
    confirm_company_delete_desc: "هل أنت متأكد تماماً من شطب شركة الأدوية نهائياً من دليل شركات التوريد والإنتاج؟",
    confirm_company_delete_btn: "تأكيد الحذف والشطب",

    // Audit Tab (سجل التدقيق والمراقبة)
    audit_tab_title: "سجل التدقيق والمراقبة التاريخية لكل علبة دواء 📋",
    audit_tab_desc: "تتبع حركات المخزون، عمليات الصرف، والتسويات اليدوية لضمان الشفافية ومكافحة الهدر والفقد",
    audit_print_all: "طباعة السجل بالكامل 🖨️",
    audit_total_records: "إجمالي الحركات المسجلة",
    audit_total_records_desc: "حركات مدققة وموقعة زمنياً",
    audit_stock_additions: "عمليات الإضافة المخزنية",
    audit_stock_additions_desc: "توليد أرصدة افتتاحية وتوريد",
    audit_dispensed_stock: "الأدوية المصروفة للمقيمين",
    audit_dispensed_stock_desc: "صرف دوائي رسمي موثق",
    audit_manual_adjustments: "التسويات والتعديلات اليدوية",
    audit_manual_adjustments_desc: "مراقبة الفروقات لتفادي الهدر",
    audit_adjustment_title: "تسجيل تسوية جرد يدوية (ضبط رصيد)",
    audit_adjustment_desc: "هذه الأداة تتيح للصيدلي تعديل كمية أي دواء يدوياً (بالزيادة لتسجيل تبرعات/توريد إضافي، أو بالنقصان لتسجيل أدوية تالفة أو مفقودة)، مع توثيق اسم المسؤول والسبب لمنع الهدر.",
    audit_target_med: "الدواء المعني بالطبيعة",
    audit_select_med_ph: "-- اختر الدواء المطلوب تسويته --",
    audit_adj_type: "نوع التسوية",
    audit_adj_type_sub: "إتلاف / عجز / مفقود (-)",
    audit_adj_type_add: "إضافة تبرع / توريد فائض (+)",
    audit_adj_qty: "الكمية المعدلة",
    audit_qty_ph: "عدد الوحدات",
    audit_reason_label: "ملاحظات وسبب التعديل (إلزامي للشفافية)",
    audit_reason_ph: "مثال: تلف الصلاحية، اكتشاف عجز جرد، فائض توريد مركز ذوي الاحتياجات...",
    audit_save_adj_btn: "حفظ وتوثيق حركة التسوية 💾",
    audit_table_title: "سجل عمليات التدقيق التاريخية الفوري",
    audit_live_badge: "تحديث فوري وتوقيع رقمي",
    audit_col_timestamp: "التوقيت والحدث",
    audit_col_med: "الدواء المعني",
    audit_col_action: "نوع الحركة",
    audit_col_change: "التعديل",
    audit_col_balance: "الرصيد الانتقالي",
    audit_col_user: "المسؤول",
    audit_col_notes: "ملاحظات التدقيق والشفافية",
    audit_no_logs: "لا توجد حركات تدقيق مسجلة حتى الآن.",

    // Skins / Themes
    skin_selector_title: "اختر مظهر النظام (Skin)",
    skin_selector_btn: "المظهر 🎨",
    skin_midnight_name: "كحلي زمردي ليلي (Midnight)",
    skin_midnight_desc: "المظهر الافتراضي الفخم عالي التباين للصيدلية",
    skin_light_name: "أبيض سريري ناصع (Daylight)",
    skin_light_desc: "مظهر نهاري سريري فائق الوضوح ومريح للقراءة",
    skin_royal_name: "كحلي ملكي وذهبي (Royal Navy)",
    skin_royal_desc: "أزرق ملكي داكن بلمسات ذهبية للإدارة العليا",
    skin_forest_name: "أخضر زمردي صحي (Forest Mint)",
    skin_forest_desc: "أجواء صيدلانية نباتية هادئة ومريحة للعين",
    skin_amethyst_name: "أرجواني نفسي حديث (Amethyst)",
    skin_amethyst_desc: "طابع بنفسجي دافئ ملائم لعيادات السلوك والنفسية",
    skin_slate_name: "فحمي فولاذي عصري (Charcoal)",
    skin_slate_desc: "مظهر داكن عصري بدرجات الرمادي الفولاذي والأزرق الثلجي",
  },
  en: {
    // Nav & Common Tabs
    app_title: "Smart Care Pharmacy",
    app_subtitle: "Medication Monitoring & Dispensing System for Special Needs",
    dashboard: "Dashboard 📊",
    inventory: "Inventory 📦",
    alternatives: "Alternatives 🔍",
    dispense: "Dispense Records 💊",
    residents: "Residents 👥",
    behavior: "Psychology & Behavior 🧠",
    companies: "Pharma Companies 🏢",
    users: "User Management ⚙️",
    welcome: "Welcome,",
    role: "Role:",
    security_level: "Security Level: Extremely High",
    client_ip: "Current Client IP:",
    logout: "Log Out",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search...",
    actions: "Actions",
    all: "All",
    no_data: "No data available currently",
    success_msg: "Action completed successfully!",

    // Dashboard Scorecard
    total_val: "Total Inventory Stock Value",
    total_items: "Total Unique Items:",
    dispensed_qty: "Total Dispensed Medications",
    dispense_count: "Total Dispense Transactions:",
    near_expiry: "Near Expiry Medications",
    alert_config: "Alert Threshold set to:",
    days_unit: "Days",
    critical_expired: "Expired / Critical Stock",
    expired_count: "Expired:",
    critical_count: "Critical:",
    dispense_unit: "Units",
    items_unit: "Items",
    emergency_cases: "Emergency Cases",

    // Dashboard Actions
    new_dispense_btn: "Record New Dispense",
    wa_report_btn: "Send Free WhatsApp Report 📲",
    simulate_alerts_btn: "Simulate Expiry Notifications",

    // Dashboard Charts
    monthly_consumption: "Monthly Medication Consumption & Dispense Rate",
    monthly_desc: "Monitor monthly quantities, dosages dispensed to residents, and their financial value",
    distribution_title: "Current Medicine Stock Distribution",
    distribution_desc: "Distribution of active medicine quantities based on therapeutic categories",
    stable_badge: "Stable",
    active_stock: "Active Stock",
    unit_qty: "Units",
    sar: "SAR",

    // Manufacturer Charts
    manufacturer_stock: "Pharmacy Inventory Analysis by Manufacturer",
    manufacturer_stock_desc: "Total financial value and quantities available in inventory per production company",
    manufacturer_dispense: "Resident Dispense & Consumption Rates by Company",
    manufacturer_dispense_desc: "Total units and treatment dosages actually dispensed belonging to each company's production",
    total_value_chart: "Financial Value (SAR)",
    total_qty_chart: "Available Stock",
    actual_dispensed_chart: "Actually Dispensed",

    // Forecasting & Near-Expiry Panels
    predictive_title: "Smart Predictive Stock Depletion System",
    predictive_desc: "Analysis of consumption rates and automatic forecasting of expected stockout dates",
    predictive_safe: "Stock levels are fully sufficient and safe for the next 60 days!",
    depletion_critical: "Critical Outage 🚨",
    depletion_warning: "Refill Needed ⚠️",
    monthly_draw: "Monthly Draw Rate:",
    available_qty: "Currently Available:",
    expected_depletion: "Expected Outage: in",
    expected_days: "Days only!",
    near_expiry_meds_title: "Medicines Closest to Expiry",
    near_expiry_safe: "All medications in the pharmacy stock are valid and undergo continuous automatic tracking.",
    expire_after: "Expires in:",
    days_left: "Days only!",
    expired_already: "Already Expired! 🚨",

    // Alternatives Directory Tab
    alternatives_title: "Smart Treatment Alternatives Directory",
    alternatives_desc: "Search any medication to instantly find its registered therapeutic alternatives and stock levels",
    search_label: "Select or search for Commercial or Scientific Name:",
    search_placeholder: "Type commercial or scientific name to search...",
    no_med_matches: "No medicines match this search",
    manufacturer_label: "Manufacturer:",
    expiry_date_label: "Expiry Date:",
    unit_price_label: "Unit Price:",
    not_defined: "Not Defined",
    available_alts_label: "Available & Suggested Treatment Alternatives in System:",
    alts_intro: "The following medications are registered as valid therapeutic alternatives that can be dispensed if needed:",
    registered_alt: "Registered Alternative Name",
    available_in_stock: "Available in Stock ✅",
    not_available_in_stock: "Out of Stock ❌",
    view_alt_details: "Click to view details of this alternative 🔍",
    no_alts_registered: "No alternatives registered for this medication",
    no_alts_registered_desc: "You can open the Inventory tab and edit the medication profile to add therapeutic alternatives.",
    no_med_selected: "No medication selected yet",
    no_med_selected_desc: "Use the search box above to choose a medicine, and the system will instantly reveal all registered alternatives and stock levels.",

    // Inventory Tab
    inventory_title: "Pharmacy Inventory & Stock Management",
    inventory_subtitle: "Register new pharmaceutical brands, set automatic alert thresholds, and track total value",
    add_new_med: "Add New Medication to Stock +",
    commercial_name: "Commercial Name",
    scientific_name: "Scientific/Generic Name",
    unit_label: "Unit Type",
    category_label: "Therapeutic Class",
    quantity: "Available Qty",
    unit_price: "Unit Price",
    expiry_date: "Expiry Date",
    registered_manufacturer: "Manufacturer",
    alt_medicines: "Therapeutic Alternatives",
    search_inventory: "Search commercial or scientific name...",
    all_categories: "All Therapeutic Classes",
    filter_stock: "Filter Quantity & Expiry Status",
    all_items: "All Stocked Items",
    critical_stock_filter: "Critical Stock (15 items & less)",
    expired_items_filter: "Expired Medications",
    expiring_soon_filter: "Expiring Soon (30 Days)",
    companies_sub_tab: "Approved Pharmaceutical Companies 🏢",
    companies_sub_desc: "Manage and register pharmaceutical manufacturers, suppliers, and official contact info",
    add_new_company: "Register New Pharma Company +",
    company_name: "Company Name",
    country: "Country of Origin",
    contact_person: "Sales Representative",
    phone: "Contact Phone",
    email: "Email Address",
    notes: "Additional Notes",
    search_companies: "Search pharma companies directory...",

    // Dispense Tab
    dispense_title: "Dispense Transactions & Daily Schedules",
    dispense_subtitle: "Monitor daily treatment dosages delivered to residents, and archive electronic signatures",
    record_new_dispense: "Record New Medication Dispensation +",
    resident_name: "Resident Name",
    dispensed_med: "Medication Dispensed",
    frequency_label: "Frequency / Daily Dose",
    quantity_dispensed: "Quantity Dispensed",
    dispense_date: "Dispensation Date",
    supervisor_sig: "Pharmacist & Supervisor Signature",
    search_dispense: "Search by resident name or medication...",
    no_records_found: "No records found matching your search.",

    // Residents Tab
    residents_title: "Resident Medical Profiles & Dosages",
    residents_subtitle: "Access comprehensive health dossiers of special needs residents, monitor schedules, and daily behaviors",
    add_new_resident: "Register New Resident +",
    resident_id: "Resident Medical ID",
    national_id: "National ID Number",
    age: "Age",
    floor_room: "Floor & Wing/Room",
    medical_condition: "Diagnosis & Medical Condition",
    emergency_phone: "Emergency Family Phone",
    actions_resident: "Medical File & Dosages 📋",
    search_residents: "Search by resident name, Medical ID, or National ID...",

    // Resident File Modal (ملف المقيم)
    resident_profile_title: "Interactive Medical dossier for:",
    resident_profile_sub: "Complete management of dosages, psychological ratings, behavior logs, and AI report generation",
    general_info_tab: "General Profile & Diagnosis 🩺",
    dosage_schedule_tab: "Prescribed Dosages & Schedule 📅",
    behavior_tracking_tab: "Behavior Rating & Mental Health 🧠",
    ai_analysis_tab: "AI Clinical Analysis & Optimization ✨",
    clinical_history: "Clinical Dosage History:",
    add_dose_btn: "Add New Prescribed Dosage +",
    daily_schedule: "Approved Active Daily Dosage Schedule:",
    dose_med_name: "Prescribed Medicine",
    dose_amount: "Prescribed Dose",
    dose_freq: "Daily Frequency",
    dose_status: "Approval & Inventory Status",
    dosage_active: "Active and Approved in File ✅",
    behavior_logs_title: "Behavior Ratings & Psychological Log:",
    add_behavior_btn: "Add New Behavior Rating +",
    behavior_rating: "Behavior Stability Level",
    behavior_notes: "Behavioral Notes & Supervision Guidance",
    behavior_date: "Evaluation Date",
    stable_green: "Stable & Normal 🟢",
    agitated_orange: "Agitated / Medium Anxiety 🟡",
    anxious_red: "Hostile / Severe Distraction 🔴",
    ai_btn_generate: "Generate Comprehensive AI Clinical Analysis ✨",
    ai_prompt_text: "Generate Smart Strategic Report for Resident:",
    ai_generating: "Analyzing medicine stock levels, parsing draw rates, matching resident files...",
    ai_report_title: "Preventative Strategic Report from Care Pharmacy System:",

    // Behavior Tab (السلوك والنفسية)
    behavior_title: "Mental Health & Behavioral Tracking Log",
    behavior_subtitle: "Interactive panel to monitor resident daily stability, document behaviors, and medical feedback",
    resident_field: "Resident",
    rating_field: "Behavior Rating",
    notes_field: "Notes & Supervision Guidance",
    date_field: "Log Timestamp",
    search_behavior: "Search by resident or behavior state...",
    behavior_rating_chart_title: "Resident Daily Behavior Stability Distribution",

    // User Settings Tab
    users_title: "Access Permissions & Federal Security Audit Logs",
    users_subtitle: "Manage accounts of pharmacists, administrators, and supervisors, and review live security audits",
    add_new_user: "Add New User Account +",
    user_name_col: "Employee Name",
    email_col: "Email Address",
    role_col: "Medical Role/Access",
    status_col: "Account Status",
    ip_allowed_col: "Allowed IPs",
    security_logs_title: "Live Security & Access Logs (Security Logs):",
    security_logs_desc: "Encrypted federal log of all sign-ins, dispense records, modifications, IP addresses, and browsers to ensure strict medical audit trails",
    timestamp_col: "Timestamp",
    user_col: "Responsible User",
    action_col: "Medical / Security Action Executed",
    ip_col: "IP Address",
    device_col: "Device & Browser Environment",
    search_users_logs: "Search by employee, IP, or executed action...",

    // Notification Channel Tab (إعدادات القنوات)
    notif_title: "Notification Gateways & Morning Scan Configuration",
    notif_subtitle: "Connect your pharmacy to WhatsApp, government emails, and schedule automatic safety checks",
    notif_whats_title: "WhatsApp Configuration & Auto Notification Gateway:",
    notif_whats_desc: "Activate automatic alerts to notify directors, supervisors, and ministry personnel on critical stocks or expired items",
    whats_enable: "Enable WhatsApp Alerts",
    whats_mode_label: "Active WhatsApp Gateway",
    whats_number_label: "Recipient WhatsApp Number (International format)",
    whats_number_placeholder: "e.g., 9665XXXXXXXX",
    ultramsg_inst_label: "UltraMsg Instance ID",
    ultramsg_tok_label: "UltraMsg Token",
    callmebot_api_label: "CallMeBot API Key",
    wapilot_api_label: "WAPilot API Token",
    notif_email_title: "Email Gateway Configuration (Google Apps Script Proxy):",
    notif_email_desc: "Connect your pharmacy to Google's approved Apps Script to dispatch periodic email digests completely free of charge",
    email_enable: "Enable Email Notifications",
    email_apps_script: "Google Apps Script Web App URL(s)",
    email_apps_script_placeholder: "Enter Apps Script URL (or separate multiple URLs with commas for auto-rotation and quota bypass)",
    recipient_email_label: "Recipient Email Address for Daily Digests",
    recipient_email_placeholder: "e.g., admin@carecenter.gov.sa",

    // Add/Edit Medicine Modals
    add_med_title: "Add New Medication to Pharmacy Inventory",
    edit_med_title: "Edit Medication in Pharmacy Inventory",
    commercial_name_req: "Commercial Name *",
    scientific_name_req: "Scientific Name *",
    unit_available: "Available Qty *",
    unit_req: "Unit *",
    add_unit_link: "+ Add Unit",
    unit_price_req: "Unit Price (SAR) *",
    expiry_date_req: "Expiry Date *",
    category_req: "Therapeutic Class *",
    add_category_link: "+ Add Class",
    manufacturer_req: "Medication Manufacturer",
    manufacturer_placeholder: "Type name or select from directory...",
    alts_label: "Therapeutic Alternatives",
    write_alt_placeholder: "Type alternative name and press Enter...",
    add_alt_btn: "Add Alt +",
    save_med_btn: "Save Medication to Inventory",
    save_edits_btn: "Save Modifications",

    // Toast & Alerts Custom
    confirm_med_delete: "Confirm Medicine Deletion",
    confirm_med_delete_desc: "Are you sure you want to permanently delete this medication from the Care Pharmacy inventory? This action cannot be undone.",
    confirm_med_delete_btn: "Permanently Delete",
    confirm_company_delete: "Confirm Company Deletion",
    confirm_company_delete_desc: "Are you sure you want to permanently delete this pharma company from the authorized directory?",
    confirm_company_delete_btn: "Permanently Delete",

    // Audit Tab
    audit_tab_title: "Historical Audit & Ledger Trail for Every Medication 📋",
    audit_tab_desc: "Track inventory transactions, dispense logs, and manual adjustments for transparency and waste prevention",
    audit_print_all: "Print Full Audit Ledger 🖨️",
    audit_total_records: "Total Logged Transactions",
    audit_total_records_desc: "Audited & time-stamped entries",
    audit_stock_additions: "Inventory Additions",
    audit_stock_additions_desc: "Opening balances & deliveries",
    audit_dispensed_stock: "Dispensed to Residents",
    audit_dispensed_stock_desc: "Official documented doses",
    audit_manual_adjustments: "Manual Adjustments",
    audit_manual_adjustments_desc: "Variance control & calibration",
    audit_adjustment_title: "Record Manual Stock Adjustment (Balance Calibration)",
    audit_adjustment_desc: "Enables pharmacists to calibrate medication quantities manually (increase for donations/excess delivery, decrease for damaged or missing units) with logged auditor identity.",
    audit_target_med: "Target Medication",
    audit_select_med_ph: "-- Select medication to adjust --",
    audit_adj_type: "Adjustment Type",
    audit_adj_type_sub: "Deficit / Damaged / Lost (-)",
    audit_adj_type_add: "Donation / Surplus Delivery (+)",
    audit_adj_qty: "Adjustment Quantity",
    audit_qty_ph: "Number of units",
    audit_reason_label: "Reason & Audit Notes (Required for transparency)",
    audit_reason_ph: "e.g., Expired batch, physical inventory variance, surplus donor delivery...",
    audit_save_adj_btn: "Save & Document Adjustment 💾",
    audit_table_title: "Live Historical Stock Audit Ledger",
    audit_live_badge: "Real-time sync & digital signature",
    audit_col_timestamp: "Timestamp & Event",
    audit_col_med: "Target Medication",
    audit_col_action: "Action Type",
    audit_col_change: "Adjustment",
    audit_col_balance: "Balance Flow",
    audit_col_user: "Auditor / Staff",
    audit_col_notes: "Audit Notes & Transparency",
    audit_no_logs: "No audit transactions logged yet.",

    // Skins / Themes
    skin_selector_title: "Select System Theme (Skin)",
    skin_selector_btn: "Skins 🎨",
    skin_midnight_name: "Midnight Emerald (Default)",
    skin_midnight_desc: "Signature dark luxury executive pharmacy theme",
    skin_light_name: "Clinical Daylight (Pure White)",
    skin_light_desc: "Ultra-crisp hospital daylight theme for maximum readability",
    skin_royal_name: "Royal Navy & Gold",
    skin_royal_desc: "Deep sapphire blue with warm gold accents for leadership",
    skin_forest_name: "Botanical Forest Mint",
    skin_forest_desc: "Soothing natural emerald green apothecary atmosphere",
    skin_amethyst_name: "Modern Amethyst Neuro",
    skin_amethyst_desc: "Warm purple palette ideal for behavioral & mental health",
    skin_slate_name: "Charcoal & Steel Ice",
    skin_slate_desc: "Minimalist dark steel with cool ice-blue accents",
  }
} as const;
